services:
  statsd-exporter:
    image: prom/statsd-exporter
    ports:
      - "8125:9125/udp"  # StatsD listens here
      - "9102:9102"      # Prometheus scrapes metrics here

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
